// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMi9sCfGWFUNDmS6k46nar_U1DVDtxGic',
    appId: '1:410889987508:web:cdfa4d05adba3f819e3ee1',
    messagingSenderId: '410889987508',
    projectId: 'attendance-system-993a5',
    authDomain: 'attendance-system-993a5.firebaseapp.com',
    databaseURL: 'https://attendance-system-993a5-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-system-993a5.appspot.com',
    measurementId: 'G-YBCWM1VMHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuY6weuU2wnShTvw--FdJLYldhldPApFI',
    appId: '1:410889987508:android:2851fc7288271dce9e3ee1',
    messagingSenderId: '410889987508',
    projectId: 'attendance-system-993a5',
    databaseURL: 'https://attendance-system-993a5-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-system-993a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcGeksv2MN_alUYWvte38kYZI3RXaQARI',
    appId: '1:410889987508:ios:7c7634a500059a4d9e3ee1',
    messagingSenderId: '410889987508',
    projectId: 'attendance-system-993a5',
    databaseURL: 'https://attendance-system-993a5-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-system-993a5.appspot.com',
    iosBundleId: 'com.example.abdi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcGeksv2MN_alUYWvte38kYZI3RXaQARI',
    appId: '1:410889987508:ios:ef36298600bbe7129e3ee1',
    messagingSenderId: '410889987508',
    projectId: 'attendance-system-993a5',
    databaseURL: 'https://attendance-system-993a5-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-system-993a5.appspot.com',
    iosBundleId: 'com.example.abdi.RunnerTests',
  );
}
